services:
  - type: web
    name: item-management-api
    env: java
    buildCommand: mvn clean package
    startCommand: java -jar target/item-management-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_VERSION
        value: 21

